In [3]:
import numpy as np

## Data Types & Attributes

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.shape

(3,)

In [9]:
arr2 = np.array(
    [[1, 2, 3],[4, 5, 6]]
)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.array(
    [
        [[1, 2, 3],[4, 5, 6]],
        [[7, 8, 9],[10, 11, 12]],
        [[13, 14, 15],[16, 17, 18]],
    ]
)
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [11]:
## Creating DataFrame From numpy arr
import pandas as pd

df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating Arrays

In [12]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [13]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 3, 1, 7, 3],
       [5, 2, 9, 2, 0],
       [5, 6, 3, 0, 0]])

In [17]:
random_array_2 = np.random.random((2,4))
random_array_2

array([[0.7604436 , 0.06682259, 0.87599032, 0.57341176],
       [0.14653854, 0.61941055, 0.54550179, 0.57509234]])

In [18]:
random_array_3 = np.random.rand(2, 4)
random_array_3

array([[0.71418319, 0.95122299, 0.48751301, 0.63712922],
       [0.20492691, 0.68306318, 0.83193002, 0.41597482]])

In [19]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(0, 10, size=(3, 5))
random_array_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

## Viewing Arrays and Matrices

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## Manipulating Arrays

### Arithmetic

In [21]:
arr1

array([1, 2, 3])

In [24]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [26]:
arr1 + ones

array([2., 3., 4.])

In [27]:
arr1 - ones

array([0., 1., 2.])

In [28]:
arr1 * ones

array([1., 2., 3.])

In [29]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2 * arr1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [36]:
arr1 / ones

array([1., 2., 3.])

In [37]:
arr2 / arr1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [38]:
arr2 // arr1

array([[1, 1, 1],
       [4, 2, 2]])

In [39]:
arr2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [40]:
np.square(arr2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [41]:
np.add(arr1, ones)

array([2., 3., 4.])

In [42]:
np.mod(arr2, arr1)

array([[0, 0, 0],
       [0, 1, 0]])

In [43]:
arr2 % arr1

array([[0, 0, 0],
       [0, 1, 0]])

### Aggregations

In [44]:
arr1

array([1, 2, 3])

In [45]:
sum(arr1)

6

In [46]:
np.sum(arr1)

6

In [47]:
massive_array = np.random.random(1000000)
massive_array[:10]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [48]:
%timeit sum(massive_array)

39.5 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [49]:
%timeit np.sum(massive_array)

175 µs ± 1.6 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [50]:
high_var_array = np.array([1, 100, 500, 1000, 5000, 10000])
low_var_array = np.array([2,3,6,7,10,11,15])

In [52]:
np.var(high_var_array), np.var(low_var_array)

(13387966.805555554, 18.20408163265306)

In [53]:
np.std(high_var_array), np.std(low_var_array)

(3658.9570652790603, 4.266624149448022)

In [54]:
np.mean(high_var_array), np.mean(low_var_array)

(2766.8333333333335, 7.714285714285714)

### Reshaping & Transposing

In [56]:
arr1.shape

(3,)

In [57]:
arr2.shape

(2, 3)

In [58]:
arr3.shape

(3, 2, 3)

In [68]:
arr2 = arr2.reshape(2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3 * arr2

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [73]:
arr2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
arr2.T.shape

(3, 2)

In [75]:
## Dot Product
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [76]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [77]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [78]:
# Element-wise (Hadamard Multiplication)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [80]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [82]:
# mat1.dot(mat2)
mat1.dot(mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

#### **Example** of Dot Product

In [83]:
np.random.seed(0)

sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [89]:
weekly_sales = pd.DataFrame(sales_amount, index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns = ["Almond", "Peanut", "Cashew"])
weekly_sales

Almond  Peanut  Cashew
Mon      12      15       0
Tue       3       3       7
Wed       9      19      18
Thu       4       6      12
Fri       1       6       7

In [87]:
prices = np.array([10, 8, 10])
prices

array([10,  8, 10])

In [95]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=["Price"], columns=["Almond", "Peanut", "Cashew"])
butter_prices

Almond  Peanut  Cashew
Price      10       8      10

In [96]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [100]:
sales_amount.shape, prices.shape

((5, 3), (3,))

In [101]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 124, 422, 208, 128])

In [103]:
weekly_sales_cal = butter_prices.dot(weekly_sales.T)
weekly_sales_cal

Mon  Tue  Wed  Thu  Fri
Price  240  124  422  208  128

In [104]:
weekly_sales["Total ($)"] = weekly_sales_cal.T
weekly_sales

Almond  Peanut  Cashew  Total ($)
Mon      12      15       0        240
Tue       3       3       7        124
Wed       9      19      18        422
Thu       4       6      12        208
Fri       1       6       7        128

### Comparison Operators

In [105]:
arr1 , arr2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [107]:
arr1 >= arr2

array([[ True,  True,  True],
       [False, False, False]])

In [108]:
arr1 < 5

array([ True,  True,  True])

### Sorting Arrays

In [111]:
np.random.seed(0)

random_arr = np.random.randint(20, size=(5,3))
random_arr

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [112]:
np.sort(random_arr)

array([[ 0, 12, 15],
       [ 3,  3,  7],
       [ 9, 18, 19],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [113]:
np.argmin(random_arr, axis=0)

array([4, 1, 0])

In [114]:
np.argmax(random_arr, axis=1)

array([1, 2, 1, 2, 2])

### Practical Example - 

<img src="numpy-images/panda.png"/>

In [117]:
# Convert Image into Numpy array
from matplotlib.image import imread 

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [120]:
panda[:3]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [122]:
panda.size

24465000

In [123]:
car = imread("numpy-images/car-photo.png")
car[:3]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [124]:
dog = imread("numpy-images/dog-photo.png")
dog[:3]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274